### PR TITLE
Added password verification field

### PR DESCRIPTION
**Pull request by suraj-goel**
I have added password verification field in the signup page.

### CODE REVIEW

**Comment by dbads** [comment]
your pr will be reviewed soon. 
There are lots of other issues out there, hunt more and more and rule the leaderboard 😀  
Good Luck.

**Comment by dbads** [comment]
In case you don't correct it, partial points will be given.

**Comment by suraj-goel** [comment]
I have fixed the redundant code.Kindly check and tell if there is any other problem.

**Comment by dbads** [comment]
Yeah.. That's fixed. You have been awarded points for this. Keep hunting more issues. :+1:  :smile:

**Pull request closed without merging**
