### PR TITLE
#135 Alert Boxes replaced at home page and profile page

### PR DESCRIPTION
**Pull request by ashwini571**

### CODE REVIEW

**Comment by dbads** [comment]
you will get half points if left like this :smile:

**Comment by ashwini571** [comment]
I think its done already.

**Comment by dbads** [comment]
you can replace alert boxes during sending the pr link. there are many alerts there,
one for unauthenticated users
one for blank pr_link
one pr submitted
already created pr etc 
:smile:  same thing to be done for all and much points :smile:

**Comment by dbads** [comment]
> I think its done already.

there are no snackbars on profile page yet

**Pull request closed without merging**
